### ISSUE TITLE
Size of LTRfootnote is not consistent with the size of footnote while using beamer

### ISSUE THREAD

**Issue by Hosein-Rahnama** [kvafa/xepersian#29]
Size of `\LTRfootnote` is not consistent with the size of `\footnote`. Consider the following minimal example.

\documentclass[hyperref={hyperfootnotes=false}]{beamer}

\usepackage{xepersian}
\settextfont{Persian Modern}

\setbeamerfont{footnote}{size=\tiny}
\begin{document}

\begin{frame}
متن اول\footnote{این یک زیرنویس پارسی است.} \\
متن دوم\LTRfootnote{This is a latin footnote.} \\
متن سوم\RTLfootnote{این هم زیرنویس پارسی دیگری است.} \\
متن چهارم\footnote{این یک زیرنویس پارسی است.}
\end{frame}

\end{document}

**Comment by ghost** [comment]
This is not really a bug. Each of the control sequences `\footnote`, `\LTRfootnote`, and `\RTLfootnote` have their own separate font setup because one may occasionally use different font attributes for each of these. Theoretically, what you are really looking for is
```tex
\setbeamerfont{footnote}{size=\tiny}
\setbeamerfont{LTRfootnote}{size=\tiny}
\setbeamerfont{RTLfootnote}{size=\tiny}
```
If this addresses your issue, then please consider closing this issue.
